#+TITLE: Ferramentas de gerenciamento TCPIP
#+AUTHOR: Luiz Tagliaferro

* Respostas da atividade de lab

** 1)

*** a)

#+BEGIN_SRC bash
   192.168.15.6
   enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
               inet 192.168.15.6  netmask 255.255.255.0  broadcast 192.168.15.255
               inet6 2804:431:cff2:e359:aeee:ed7:b035:8547  prefixlen 64  scopeid 0x0<global>
               inet6 fe80::8353:5627:d855:35ad  prefixlen 64  scopeid 0x20<link>
               ether 34:97:f6:e9:d6:fb  txqueuelen 1000  (Ethernet)
               RX packets 422700  bytes 305469723 (291.3 MiB)
               RX errors 0  dropped 1  overruns 0  frame 0
               TX packets 308581  bytes 58556640 (55.8 MiB)
               TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
#+END_SRC

*** b)
    O endereço mostrado era diferente. Porque nosso IP visto na rede
    de computadores é o do provedor de internet e o outro IP é somente
    o IP local.

*** c)
    É endereço pelo qual todo o tráfego de minha rede local passa para
    se conectar com outras redes.


** 2)

*** a)

#+BEGIN_SRC bash
    ~ ping www.ietr.fr
   PING vmebene3.univ-rennes1.fr (129.20.134.3) 56(84) bytes of data.
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=1 ttl=51 time=208 ms
   64 bytes fro
   m vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=2 ttl=51 time=209 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=3 ttl=51 time=206 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=4 ttl=51 time=207 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=5 ttl=51 time=207 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=6 ttl=51 time=212 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=7 ttl=51 time=207 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=8 ttl=51 time=208 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=9 ttl=51 time=208 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=10 ttl=51 time=208 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=11 ttl=51 time=219 ms
   64 bytes from vmebene3.univ-rennes1.fr (129.20.134.3): icmp_seq=12 ttl=51 time=207 ms

   --- vmebene3.univ-rennes1.fr ping statistics ---
   12 packets transmitted, 12 received, 0% packet loss, time 11317ms
   rtt min/avg/max/mdev = 205.632/208.676/219.232/3.533 ms
#+End_SRC

*** b)
    A variável time informa o tempo de reposta do servidor para com o
    cliente.

*** c)
    O TTL significa "Time to Live" e representa a quantidade de
    roteadores ou saltos que seu pacote passou para chegar ao servidor
    de destino decrementando o valor que o destino retornou sendo o
    padrao do S.O: 255 - sistema operacional unix 128.

*** d)
    Podemos utilzar-lo como parametro de conectividade com outras
    redes, pois caso o comando retorne falha na conecçao ou falta de,
    ja temos como saber o problema.


** 3)

*** a)
    Usando o comando sem o parametro "n" é retornado protocolo
    juntamenten com seu servidor DNS no fomato escrito e com ele
    mostra o numero do servidor DNS

** 4)

#+BEGIN_SRC bash

   % [whois.apnic.net]
   % Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

   % Information related to '103.115.76.0 - 103.115.79.255'

   % Abuse contacts for '103.115.76.0 - 103.115.79.255' are 'email@seagroup.com', 'email@seagroup.com'

   inetnum:        103.115.76.0 - 103.115.79.255
   netname:        SHOPEE-SG
   descr:          SHOPEE SINGAPORE PRIVATE LIMITED
   country:        SG
   org:            ORG-SSPL12-AP
   admin-c:        SSPL16-AP
   tech-c:         SSPL16-AP
   abuse-c:        AS2394-AP
   status:         ALLOCATED PORTABLE
   remarks:        --------------------------------------------------------
   remarks:        To report network abuse, please contact mnt-irt
   remarks:        For troubleshooting, please contact tech-c and admin-c
   remarks:        Report invalid contact via www.apnic.net/invalidcontact
   remarks:        --------------------------------------------------------
   mnt-by:         APNIC-HM
   mnt-lower:      MAINT-SHOPEE-SG
   mnt-routes:     MAINT-SHOPEE-SG
   mnt-irt:        IRT-SHOPEE-SG
   last-modified:  2020-06-24T11:30:32Z
   source:         APNIC

   irt:            IRT-SHOPEE-SG
   address:        1 Fusionopolis Place, # 17-10, Galaxis, SINGAPORE 138522
   e-mail:         email@seagroup.com
   e-mail:         email@seagroup.com
   abuse-mailbox:  email@seagroup.com
   abuse-mailbox:  email@seagroup.com
   admin-c:        SSPL16-AP
   tech-c:         SSPL16-AP
   auth:           # Filtered
   remarks:        email@seagroup.com was validated on 2020-06-24
   remarks:        email@seagroup.com was validated on 2020-07-03
   mnt-by:         MAINT-SHOPEE-SG
   last-modified:  2020-07-03T02:19:05Z
   source:         APNIC

   organisation:   ORG-SSPL12-AP
   org-name:       SHOPEE SINGAPORE PRIVATE LIMITED
   country:        SG
   address:        1 Fusionopolis Place, # 17-10, Galaxis
   phone:          +65-6270-8100
   e-mail:         email@seagroup.com
   mnt-ref:        APNIC-HM
   mnt-by:         APNIC-HM
   last-modified:  2019-10-25T12:56:58Z
   source:         APNIC

   role:           ABUSE SHOPEESG
   address:        1 Fusionopolis Place, # 17-10, Galaxis, SINGAPORE 138522
   country:        ZZ
   phone:          +000000000
   e-mail:         email@seagroup.com
   e-mail:         email@seagroup.com
   admin-c:        SSPL16-AP
   tech-c:         SSPL16-AP
   nic-hdl:        AS2394-AP
   remarks:        Generated from irt object IRT-SHOPEE-SG
   abuse-mailbox:  email@seagroup.com
   abuse-mailbox:  email@seagroup.com
   mnt-by:         APNIC-ABUSE
   last-modified:  2020-06-24T11:30:31Z
   source:         APNIC

   role:           SHOPEE SINGAPORE PRIVATE LIMITED administrator
   address:        1 Fusionopolis Place, #17-10, Galaxis, SINGAPORE  138522
   country:        SG
   phone:          +65-6270-8100
   fax-no:         +65-6270-8100
   e-mail:         email@shopee.com
   admin-c:        SSPL16-AP
   tech-c:         SSPL16-AP
   nic-hdl:        SSPL16-AP
   mnt-by:         MAINT-SHOPEE-SG
   last-modified:  2018-05-14T04:34:20Z
   source:         APNIC

   % Information related to '103.115.78.0/24AS138341'

   route:          103.115.78.0/24
   origin:         AS138341
   descr:          SHOPEE SINGAPORE PRIVATE LIMITED
                   1 Fusionopolis Place, #17-10, Galaxis
   mnt-by:         MAINT-SHOPEE-SG
   last-modified:  2018-12-06T07:21:05Z
   source:         APNIC

   % This query was served by the APNIC Whois Service version 1.88.15-SNAPSHOT (WHOIS-US3)
#+END_SRC

** 5)

*** a)

#+BEGIN_SRC bash
     ~ tracepath -b www.lsi.usp.br
     1?: [LOCALHOST]                      pmtu 1492
     1:  _gateway (192.168.15.1)                               0.360ms
     1:  _gateway (192.168.15.1)                               0.232ms
     2:  no reply
     3:  187-100-176-230.dsl.telesp.net.br (187.100.176.230)   2.220ms
     4:  152-255-177-85.user.vivozap.com.br (152.255.177.85)   4.972ms
     5:  187-100-53-194.dsl.telesp.net.br (187.100.53.194)    28.516ms
     6:  as28571.saopaulo.sp.ix.br (187.16.216.20)             8.028ms asymm  5
     7:  core-cce.uspnet.usp.br (143.107.251.30)               6.160ms asymm  5
     8:  no reply
     9:  no reply
    10:  www.lsi.usp.br (143.107.161.160)                      4.348ms reached
         Resume: pmtu 1492 hops 10 back 8
#+END_SRC

*** b)
    Passou por 7 IPs diferentes

*** c)
    Sim. Porque alguns IPs por questao de segurança sao ocultos

*** d)
    Obtive o seguinte output:

#+BEGIN_SRC bash

   Usage
     tracepath [options] <destination>

    Options:
      -4             use IPv4
      -6             use IPv6
      -b             print both name and ip
      -l <length>    use packet <length>
      -m <hops>      use maximum <hops>
      -n             no dns name resolution
      -p <port>      use destination <port>
      -V             print version and exit
      <destination>  dns name or ip address

    For more details see tracepath(8).
#+END_SRC


** 6)
#+BEGIN_SRC bash
   ~ tracepath www.ietr.fr
    1?: [LOCALHOST]                      pmtu 1492
    1:  _gateway                                              0.362ms
    1:  _gateway                                              0.412ms
    2:  no reply
    3:  187-100-176-222.dsl.telesp.net.br                     6.441ms
    4:  no reply
    5:  152-255-171-234.user.vivozap.com.br                   2.957ms
    6:  ???                                                  13.761ms asymm  7
    7:  ???                                                 120.904ms
    8:  ???                                                 129.252ms asymm  7
    9:  ae5.cr6-mia1.ip4.gtt.net                            118.004ms
   10:  et-3-3-0.cr4-par7.ip4.gtt.net                       219.657ms asymm 16
   11:  renater-gw-ix1.gtt.net                              221.931ms asymm 14
   12:  te0-1-0-1-ren-nr-caen-rtr-091.noc.renater.fr        211.502ms asymm 13
   13:  te0-1-0-9-ren-nr-rennes-rtr-091.noc.renater.fr      231.452ms asymm 15
   14:  et-3-3-0.cr4-par7.ip4.gtt.net                       218.816ms asymm 16
   15:  no reply
   16:  no reply
   17:  no reply
   18:  no reply
   19:  no reply
   20:  no reply
   21:  no reply
   22:  no reply
   23:  no reply
   24:  no reply
   25:  no reply
   26:  no reply
   27:  no reply
   28:  no reply
   29:  no reply
   30:  no reply
        Too many hops: pmtu 1492
        Resume: pmtu 1492
#+END_SRC


#+BEGIN_SRC
%%
%% This is the AFNIC Whois server.
%%
%% complete date format : YYYY-MM-DDThh:mm:ssZ
%% short date format    : DD/MM
%% version              : FRNIC-2.5
%%
%% Rights restricted by copyright.
%% See https://www.afnic.fr/en/products-and-services/services/whois/whois-special-notice/
%%
%% Use '-h' option to obtain more information about this service.
%%
%% [REQUEST] >> ietr.fr
%%
%% RL Net [##########] - RL IP [#########.]
%%

domain:      ietr.fr
status:      ACTIVE
hold:        NO
holder-c:    UDRU26-FRNIC
admin-c:     UDRU20-FRNIC
tech-c:      UDRU21-FRNIC
zone-c:      NFC1-FRNIC
nsl-id:      NSL56926-FRNIC
registrar:   NAMESHIELD
Expiry Date: 2020-09-18T09:02:23Z
created:     2009-03-05T15:23:51Z
last-update: 2019-09-16T22:10:50Z
source:      FRNIC

ns-list:     NSL56926-FRNIC
nserver:     soleil.uvsq.fr
nserver:     resone.univ-rennes1.fr
source:      FRNIC
#+END_SRC


** 7)

*** a)
    Vivo

*** b)
    Fibra

*** c)
    Download 340 Mbit/s   Upload 168 Mbit/s

*** d)
    10 ms. Representa o tempo de resposta do servidor

*** e)
    Jitter 4ms. É a medida de variaçao de atraso entre os pacotes

*** f)
    Realizei todos os testes no PC via cabo, porem caso fosse via
    WIFI, dependendo do dositivo em que fosse realizado o teste,
    ocorreriam variaçoes de sinal por conta da instabilidade do sinal.
    Causando mediçoes imprecisas e que podem nao estar de acordo com a
    largura de banda contrada com o provedor

*** g)
